{% set name = "marxs" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb9fb2ed73f8e0fc32c6b8ee76888cbcdd6fdfec66347d04c104d6f8dca9debf
  patches:
    - setup.cfg.patch

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
    - astropy
    - transforms3d
  run:
    - python
    - astropy
    - transforms3d
    - scipy

test:
  imports:
    - marxs
    - marxs.analysis
    - marxs.base
    - marxs.design
    - marxs.math
    - marxs.missions
    - marxs.optics
    - marxs.simulator
    - marxs.source
    - marxs.visualization

about:
  home: https://github.com/Chandra-MARX/marxs
  license: GPLv3+
  license_family: GPL3
  license_file: licenses/LICENSE.rst
  summary: Multi Architecture Raytracer for X-ray satellites
  description: |
    MARXS (Multi-Architecture-Raytrace-Xraymission-Simulator) is a toolsuite
    to simulate the performance X-ray observatories. It is primarily aimed at
    astronomical X-ray satellites and sounding rocket payloads, but can be
    used to ray-trace experiments in the laboratory as well. MARXS performs
    Monte-Carlo ray-trace simulations from a source (astronomical or lab)
    through a collection of optical elements such as mirrors, baffles, and
    gratings to a detector.
  doc_url: http://marxs.readthedocs.io/en/latest/
  dev_url: https://github.com/Chandra-MARX/marxs

extra:
  recipe-maintainers:
    - mwcraig
