travis:
  secure:
    BINSTAR_TOKEN: kTp8B4J4Y5uX40GVddLj3xtFvnxnQZs33A9cxRxUdS44kvfyD2O5GbiWigNgbM9s00J5ziZYy7G6CJeZ+Hjo5EttU/ylJchPcKWtJkdwi7ezj4e53o7bwH8sWmsTmz67RDmj8NXYTwMJTaTJDKZwFH6xgm12d0q9LXvXZg6Y75LSkGNVPPsq9O7jqV8ECIEu6hGoKpikpueN65oN9JwHWXK9ikn+bZ97hdynoEosVdk5B3YuMyYH+AgidUQQsdMODGI7iCw71tTDqBtews1zDOyXejVZR2zcQPqltARvKLvmGn1qIgCuTgdP8EGLaA87866VFsb3pN3e83SbDP/rQaNg9hTEplnq7XNw2cXTaYHs9OWQqElG5hy9v5jFxOaI7w4jFzYplLWQCk8XduEqx0CK+HPEltCRp2O4psjJKqoJb0uTt7Iu2CDCeY1Us5UZpb4BKs+8dmqb0SvqAeuZtf91dQrfnzyHVRzK2VHP4oojHHUEoYP/qSsBvnCxQU2HTKht5K2CBZlIuKlADiVH19wsBO7bloqHXQhS0fSIRQtFXuOiGNOLltviePA2GP8zJ/wkjAXLi2Z98H1C+x4dG5KsX+uopZpzydBKSxFkM3yxMdAU/+0s9UosAO55lZ2QB4dPWkRC2ua4OczxqvU+EQF5utK5OJY0oNVnX6tSzJY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
